/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProspectionRouteImport } from './routes/prospection'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as EtudesRouteImport } from './routes/etudes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ProspectionRoute = ProspectionRouteImport.update({
  id: '/prospection',
  path: '/prospection',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudesRoute = EtudesRouteImport.update({
  id: '/etudes',
  path: '/etudes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/etudes': typeof EtudesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/opportunites': typeof OpportunitesRoute
  '/prospection': typeof ProspectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/etudes': typeof EtudesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/opportunites': typeof OpportunitesRoute
  '/prospection': typeof ProspectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/etudes': typeof EtudesRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/opportunites': typeof OpportunitesRoute
  '/prospection': typeof ProspectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/etudes'
    | '/leads'
    | '/login'
    | '/opportunites'
    | '/prospection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/etudes'
    | '/leads'
    | '/login'
    | '/opportunites'
    | '/prospection'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/etudes'
    | '/leads'
    | '/login'
    | '/opportunites'
    | '/prospection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  EtudesRoute: typeof EtudesRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  OpportunitesRoute: typeof OpportunitesRoute
  ProspectionRoute: typeof ProspectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prospection': {
      id: '/prospection'
      path: '/prospection'
      fullPath: '/prospection'
      preLoaderRoute: typeof ProspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudes': {
      id: '/etudes'
      path: '/etudes'
      fullPath: '/etudes'
      preLoaderRoute: typeof EtudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  EtudesRoute: EtudesRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  OpportunitesRoute: OpportunitesRoute,
  ProspectionRoute: ProspectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
